const dataBase = [
    {
        name: "Water",
        cid: 962,
        translate: "آب",
        iupacName: "oxidane",
        molecularFormula: "H2O",
        smiles: "O",
        molecularWeight: "18.015 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "99.97 °C",
        meltingPoint: "0.00 °C",
        density: "اطلاعات دقیقی در دسترس نیست"
    },
    {
        name: "Oxygen",
        cid: 977,
        translate: "اکسیژن",
        iupacName: "molecular oxygen",
        molecularFormula: "O2",
        smiles: "O=O",
        molecularWeight: "31.999 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "-183.00 °C",
        meltingPoint: "-218.33 °C",
        density: "0.001 g/cm³"
    },
    {
        name: "Nitrogen",
        cid: 947,
        translate: "نیتروژن",
        iupacName: "molecular nitrogen",
        molecularFormula: "N2",
        smiles: "N#N",
        molecularWeight: "28.014 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "-196.00 °C",
        meltingPoint: "-210.00 °C",
        density: "0.001 g/cm³"
    },
    {
        name: "Carbon Dioxide",
        cid: 280,
        translate: "دی‌اکسید کربن",
        iupacName: "ندارد",
        molecularFormula: "CO2",
        smiles: "C(=O)=O",
        molecularWeight: "44.009 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "-78.46 °C",
        meltingPoint: "-56.50 °C",
        density: "0.002 g/cm³"
    },
    {
        name: "Ozone",
        cid: 24823,
        translate: "اوزون",
        iupacName: "ozone",
        molecularFormula: "O3",
        smiles: "[O-][O+]=O",
        molecularWeight: "47.998 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "-112.00 °C",
        meltingPoint: "-193.00 °C",
        density: "اطلاعات دقیقی در دسترس نیست"
    },
    {
        name: "Methane",
        cid: 297,
        translate: "متان",
        iupacName: "methane",
        molecularFormula: "CH4",
        smiles: "C",
        molecularWeight: "16.043 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "-161.00 °C",
        meltingPoint: "-183.00 °C",
        density: "اطلاعات دقیقی در دسترس نیست"
    },
    {
        name: "Acetylene",
        cid: 6326,
        translate: "اتین (استیلن)",
        iupacName: "acetylene",
        molecularFormula: "C2H2",
        smiles: "C#C",
        molecularWeight: "26.04 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "-84.00 °C",
        meltingPoint: "-83.89 °C",
        density: "اطلاعات دقیقی در دسترس نیست"
    },
    {
        name: "Ethylene",
        cid: 6325,
        translate: "اتن (اتیلن)",
        iupacName: "ethene",
        molecularFormula: "C2H4",
        smiles: "C=C",
        molecularWeight: "28.05 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "-104.00 °C",
        meltingPoint: "-169.00 °C",
        density: "اطلاعات دقیقی در دسترس نیست"
    },
    {
        name: "Butane",
        cid: 7843,
        translate: "بوتان",
        iupacName: "butane",
        molecularFormula: "C4H10",
        smiles: "CCCC",
        molecularWeight: "58.12 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "-0.56 °C",
        meltingPoint: "-138.00 °C",
        density: "اطلاعات دقیقی در دسترس نیست"
    },
    {
        name: "Cyclohexane",
        cid: 8078,
        translate: "سیکلوهگزان",
        iupacName: "cyclohexane",
        molecularFormula: "C6H12",
        smiles: "C1CCCCC1",
        molecularWeight: "84.16 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "81.00 °C",
        meltingPoint: "7.00 °C",
        density: "اطلاعات دقیقی در دسترس نیست"
    },
    {
        name: "Ammonia",
        cid: 222,
        translate: "آمونیاک",
        iupacName: "azane",
        molecularFormula: "H3N",
        smiles: "N",
        molecularWeight: "17.031 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "-33.00 °C",
        meltingPoint: "-78.00 °C",
        density: "0.001 g/cm³"
    },
    {
        name: "Carbon Monoxide",
        cid: 281,
        translate: "مونوکسید کربن",
        iupacName: "carbon monoxide",
        molecularFormula: "CO",
        smiles: "[C-]#[O+]",
        molecularWeight: "28.010 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "-191.00 °C",
        meltingPoint: "-205.00 °C",
        density: "0.001 g/cm³"
    },
    {
        name: "Hydrogen Peroxide",
        cid: 784,
        translate: "هیدروژن پراکسید",
        iupacName: "hydrogen peroxide",
        molecularFormula: "H2O2",
        smiles: "OO",
        molecularWeight: "34.015 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "141.11 °C",
        meltingPoint: "-11.11 °C",
        density: "اطلاعات دقیقی در دسترس نیست"
    },
    {
        name: "Carbonyl Sulfide",
        cid: 10039,
        translate: "کربونیل سولفید",
        iupacName: "ندارد",
        molecularFormula: "COS",
        smiles: "C(=O)=S",
        molecularWeight: "60.08 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "-50.00 °C",
        meltingPoint: "-50.22 °C",
        density: "0.002 g/cm³"
    },
    {
        name: "Dinitrogen Oxide",
        cid: 948,
        translate: "دی‌نیتروژن اکسید",
        iupacName: "nitrous oxide",
        molecularFormula: "N2O",
        smiles: "[N-]=[N+]=O",
        molecularWeight: "44.013 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "-88.33 °C",
        meltingPoint: "55.56 °C",
        density: "0.002 g/cm³"
    },
    {
        name: "Hydrochloric Acid",
        cid: 313,
        translate: "هیدروکلریک اسید (جوهر نمک)",
        iupacName: "chlorane",
        molecularFormula: "ClH",
        smiles: "Cl",
        molecularWeight: "36.46 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "-85.00 °C",
        meltingPoint: "-114.44 °C",
        density: "0.002 g/cm³"
    },
    {
        name: "Sulfuric Acid",
        cid: 1118,
        translate: "سولفوریک اسید",
        iupacName: "sulfuric acid",
        molecularFormula: "H2O4S",
        smiles: "OS(=O)(=O)O",
        molecularWeight: "98.08 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "337.00 °C",
        meltingPoint: "10.00 °C",
        density: "اطلاعات دقیقی در دسترس نیست"
    },
    {
        name: "Nitric Acid",
        cid: 944,
        translate: "نیتریک اسید",
        iupacName: "nitric acid",
        molecularFormula: "HNO3",
        smiles: "[N+](=O)(O)[O-]",
        molecularWeight: "63.013 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "83.00 °C",
        meltingPoint: "-42.22 °C",
        density: "اطلاعات دقیقی در دسترس نیست"
    },
    {
        name: "Phosphoric Acid",
        cid: 1004,
        translate: "فسفریک اسید",
        iupacName: "phosphoric acid",
        molecularFormula: "H3O4P",
        smiles: "OP(=O)(O)O",
        molecularWeight: "97.995 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "407.00 °C",
        meltingPoint: "42.00 °C",
        density: "1.900 g/cm³"
    },
    {
        name: "Formic Acid",
        cid: 284,
        translate: "فورمیک اسید (متانوئیک اسید)",
        iupacName: "formic acid",
        molecularFormula: "CH2O2",
        smiles: "C(=O)O",
        molecularWeight: "46.025 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "101.00 °C",
        meltingPoint: "8.00 °C",
        density: "اطلاعات دقیقی در دسترس نیست"
    },
    {
        name: "Acetic Acid",
        cid: 176,
        translate: "استیک اسید (اتانوییک اسید)",
        iupacName: "acetic acid",
        molecularFormula: "C2H4O2",
        smiles: "CC(=O)O",
        molecularWeight: "60.05 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "118.00 °C",
        meltingPoint: "16.67 °C",
        density: "اطلاعات دقیقی در دسترس نیست"
    },
    {
        name: "Hydrocyanic Acid",
        cid: 768,
        translate: "هیدروسیانیک اسید",
        iupacName: "formonitrile",
        molecularFormula: "CHN",
        smiles: "C#N",
        molecularWeight: "27.025 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "25.63 °C",
        meltingPoint: "-13.28 °C",
        density: "اطلاعات دقیقی در دسترس نیست"
    },
    {
        name: "Hydrofluoric Acid",
        cid: 14917,
        translate: "هیدروفلوئوریک اسید",
        iupacName: "fluorane",
        molecularFormula: "FH",
        smiles: "F",
        molecularWeight: "20.0064 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "20.00 °C",
        meltingPoint: "-83.00 °C",
        density: "اطلاعات دقیقی در دسترس نیست"
    },
    {
        name: "Hydrobromic Acid",
        cid: 260,
        translate: "هیدروبرمیک اسید",
        iupacName: "bromane",
        molecularFormula: "BrH",
        smiles: "Br",
        molecularWeight: "80.91 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "-67.00 °C",
        meltingPoint: "-87.00 °C",
        density: "0.003 g/cm³"
    },
    {
        name: "Hydroiodic Acid",
        cid: 24841,
        translate: "هیدرویدیک اسید",
        iupacName: "iodane",
        molecularFormula: "HI",
        smiles: "I",
        molecularWeight: "127.9124 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "-35.50 °C",
        meltingPoint: "-50.80 °C",
        density: "0.006 g/cm³"
    },
    {
        name: "Carbonic Acid",
        cid: 767,
        translate: "کربنیک اسید",
        iupacName: "carbonic acid",
        molecularFormula: "CH2O3",
        smiles: "C(=O)(O)O",
        molecularWeight: "62.025 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "اطلاعات دقیقی در دسترس نیست",
        meltingPoint: "720.00 °C",
        density: "اطلاعات دقیقی در دسترس نیست"
    },
    {
        name: "Methanol",
        cid: 887,
        translate: "متانول (الکل چوب)",
        iupacName: "methanol",
        molecularFormula: "CH4O",
        smiles: "CO",
        molecularWeight: "32.042 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "65.00 °C",
        meltingPoint: "-98.00 °C",
        density: "اطلاعات دقیقی در دسترس نیست"
    },
    {
        name: "Ethanol",
        cid: 702,
        translate: "اتانول (الکل طبی)",
        iupacName: "ethanol",
        molecularFormula: "C2H6O",
        smiles: "CCO",
        molecularWeight: "46.07 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "اطلاعات دقیقی در دسترس نیست",
        meltingPoint: "اطلاعات دقیقی در دسترس نیست",
        density: "اطلاعات دقیقی در دسترس نیست"
    },
    {
        name: "Ethylene Glycol",
        cid: 174,
        translate: "اتیلن گلیکول (ضدیخ)",
        iupacName: "ethane-1,2-diol",
        molecularFormula: "C2H6O2",
        smiles: "C(CO)O",
        molecularWeight: "62.07 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "اطلاعات دقیقی در دسترس نیست",
        meltingPoint: "اطلاعات دقیقی در دسترس نیست",
        density: "اطلاعات دقیقی در دسترس نیست"
    },
    {
        name: "Acetone",
        cid: 180,
        translate: "استون (پروپانون)",
        iupacName: "propan-2-one",
        molecularFormula: "C3H6O",
        smiles: "CC(=O)C",
        molecularWeight: "58.08 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "56.00 °C",
        meltingPoint: "-95.00 °C",
        density: "اطلاعات دقیقی در دسترس نیست"
    },
    {
        name: "Benzaldehyde",
        cid: 240,
        translate: "بنزآلدهید (موجود در بادام)",
        iupacName: "benzaldehyde",
        molecularFormula: "C7H6O",
        smiles: "C1=CC=C(C=C1)C=O",
        molecularWeight: "106.12 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "اطلاعات دقیقی در دسترس نیست",
        meltingPoint: "-26.00 °C",
        density: "اطلاعات دقیقی در دسترس نیست"
    },
    {
        name: "2-Heptanone",
        cid: 8055,
        translate: "هپتانون-۲ (موجود در میخک)",
        iupacName: "butoxymethanedithioic acid",
        molecularFormula: "C5H10OS2",
        smiles: "CCCCOC(=S)S",
        molecularWeight: "150.3 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "اطلاعات دقیقی در دسترس نیست",
        meltingPoint: "اطلاعات دقیقی در دسترس نیست",
        density: "اطلاعات دقیقی در دسترس نیست"
    },
    {
        name: "Aspirin",
        cid: 2244,
        translate: "آسپرین",
        iupacName: "2-acetyloxybenzoic acid",
        molecularFormula: "C9H8O4",
        smiles: "CC(=O)OC1=CC=CC=C1C(=O)O",
        molecularWeight: "180.16 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "اطلاعات دقیقی در دسترس نیست",
        meltingPoint: "135.00 °C",
        density: "اطلاعات دقیقی در دسترس نیست"
    },
    {
        name: "Glucose",
        cid: 5793,
        translate: "گلوکز",
        iupacName: "(3R,4S,5S,6R)-6-(hydroxymethyl)oxane-2,3,4,5-tetrol",
        molecularFormula: "C6H12O6",
        smiles: "C([C@@H]1[C@H]([C@@H]([C@H](C(O1)O)O)O)O)O",
        molecularWeight: "180.16 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "اطلاعات دقیقی در دسترس نیست",
        meltingPoint: "اطلاعات دقیقی در دسترس نیست",
        density: "اطلاعات دقیقی در دسترس نیست"
    },
    {
        name: "Maltose",
        cid: 6255,
        translate: "مالتوز (قند جوانه گندم)",
        iupacName: "(2R,3S,4S,5R,6R)-2-(hydroxymethyl)-6-[(2R,3S,4R,5R,6R)-4,5,6-trihydroxy-2-(hydroxymethyl)oxan-3-yl]oxyoxane-3,4,5-triol",
        molecularFormula: "C12H22O11",
        smiles: "C([C@@H]1[C@H]([C@@H]([C@H]([C@H](O1)O[C@@H]2[C@H](O[C@H]([C@@H]([C@H]2O)O)O)CO)O)O)O)O",
        molecularWeight: "342.30 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "اطلاعات دقیقی در دسترس نیست",
        meltingPoint: "اطلاعات دقیقی در دسترس نیست",
        density: "اطلاعات دقیقی در دسترس نیست"
    },
    {
        name: "Oleic Acid",
        cid: 445639,
        translate: "روغن زیتون",
        iupacName: "(Z)-octadec-9-enoic acid",
        molecularFormula: "C18H34O2",
        smiles: "CCCCCCCC/C=C\\CCCCCCCC(=O)O",
        molecularWeight: "282.5 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "اطلاعات دقیقی در دسترس نیست",
        meltingPoint: "16.30 °C",
        density: "اطلاعات دقیقی در دسترس نیست"
    },
    {
        name: "Stearin",
        cid: 11146,
        translate: "چربی کوهان شتر",
        iupacName: "2,3-di(octadecanoyloxy)propyl octadecanoate",
        molecularFormula: "C57H110O6",
        smiles: "CCCCCCCCCCCCCCCCCC(=O)OCC(COC(=O)CCCCCCCCCCCCCCCCC)OC(=O)CCCCCCCCCCCCCCCCC",
        molecularWeight: "891.5 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "اطلاعات دقیقی در دسترس نیست",
        meltingPoint: "اطلاعات دقیقی در دسترس نیست",
        density: "اطلاعات دقیقی در دسترس نیست"
    },
    {
        name: "Benzene",
        cid: 241,
        translate: "بنزن",
        iupacName: "benzene",
        molecularFormula: "C6H6",
        smiles: "C1=CC=CC=C1",
        molecularWeight: "78.11 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "اطلاعات دقیقی در دسترس نیست",
        meltingPoint: "اطلاعات دقیقی در دسترس نیست",
        density: "اطلاعات دقیقی در دسترس نیست"
    },
    {
        name: "Naphthalene",
        cid: 931,
        translate: "نفتالن",
        iupacName: "naphthalene",
        molecularFormula: "C10H8",
        smiles: "C1=CC=C2C=CC=CC2=C1",
        molecularWeight: "128.17 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "218.00 °C",
        meltingPoint: "اطلاعات دقیقی در دسترس نیست",
        density: "1.160 g/cm³"
    },
    {
        name: "p-Xylene",
        cid: 7809,
        translate: "پارازایلن",
        iupacName: "1,4-xylene",
        molecularFormula: "C8H10",
        smiles: "CC1=CC=C(C=C1)C",
        molecularWeight: "106.16 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "اطلاعات دقیقی در دسترس نیست",
        meltingPoint: "اطلاعات دقیقی در دسترس نیست",
        density: "اطلاعات دقیقی در دسترس نیست"
    },
    {
        name: "Styrene",
        cid: 7501,
        translate: "استایرن",
        iupacName: "styrene",
        molecularFormula: "C8H8",
        smiles: "C=CC1=CC=CC=C1",
        molecularWeight: "104.15 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "اطلاعات دقیقی در دسترس نیست",
        meltingPoint: "اطلاعات دقیقی در دسترس نیست",
        density: "اطلاعات دقیقی در دسترس نیست"
    },
    {
        name: "Propene",
        cid: 8252,
        translate: "پروپن",
        iupacName: "prop-1-ene",
        molecularFormula: "C3H6",
        smiles: "CC=C",
        molecularWeight: "42.08 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "-48.00 °C",
        meltingPoint: "اطلاعات دقیقی در دسترس نیست",
        density: "اطلاعات دقیقی در دسترس نیست"
    },
    {
        name: "Octadecane",
        cid: 11635,
        translate: "گریس",
        iupacName: "octadecane",
        molecularFormula: "C18H38",
        smiles: "CCCCCCCCCCCCCCCCCC",
        molecularWeight: "254.5 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "اطلاعات دقیقی در دسترس نیست",
        meltingPoint: "اطلاعات دقیقی در دسترس نیست",
        density: "اطلاعات دقیقی در دسترس نیست"
    },
    {
        name: "Petrolatum",
        cid: 11137,
        translate: "وازلین",
        iupacName: "3-nitrophenol",
        molecularFormula: "C6H5NO3",
        smiles: "C1=CC(=CC(=C1)O)[N+](=O)[O-]",
        molecularWeight: "139.11 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "194.00 °C",
        meltingPoint: "اطلاعات دقیقی در دسترس نیست",
        density: "اطلاعات دقیقی در دسترس نیست"
    },
    {
        name: "Sodium Hydroxide",
        cid: 14798,
        translate: "سدیم هیدروکسید (سود سوزآور)",
        iupacName: "sodium;hydroxide",
        molecularFormula: "HNaO",
        smiles: "[OH-].[Na+]",
        molecularWeight: "39.997 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 2,
        boilingPoint: "1388.00 °C",
        meltingPoint: "اطلاعات دقیقی در دسترس نیست",
        density: "اطلاعات دقیقی در دسترس نیست"
    },
    {
        name: "Potassium Hydroxide",
        cid: 14797,
        translate: "پتاسیم هیدروکسید (پتاس سوزآور)",
        iupacName: "potassium;hydroxide",
        molecularFormula: "HKO",
        smiles: "[OH-].[K+]",
        molecularWeight: "56.106 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 2,
        boilingPoint: "1327.00 °C",
        meltingPoint: "380.00 °C",
        density: "2.040 g/cm³"
    },
    {
        name: "Sodium Bicarbonate",
        cid: 516892,
        translate: "سدیم هیدروژن کربنات (جوش شیرین)",
        iupacName: "sodium;hydrogen carbonate",
        molecularFormula: "CHNaO3",
        smiles: "C(=O)(O)[O-].[Na+]",
        molecularWeight: "84.007 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 2,
        boilingPoint: "اطلاعات دقیقی در دسترس نیست",
        meltingPoint: "اطلاعات دقیقی در دسترس نیست",
        density: "2.100 g/cm³"
    },
    {
        name: "Calcium Oxide",
        cid: 14779,
        translate: "آهک (کلسیم اکسید)",
        iupacName: "calcium;peroxide",
        molecularFormula: "CaO2",
        smiles: "[O-][O-].[Ca+2]",
        molecularWeight: "72.08 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 2,
        boilingPoint: "اطلاعات دقیقی در دسترس نیست",
        meltingPoint: "اطلاعات دقیقی در دسترس نیست",
        density: "اطلاعات دقیقی در دسترس نیست"
    },
    {
        name: "Calcium Carbonate",
        cid: 10112,
        translate: "کربنات کلسیم",
        iupacName: "calcium;carbonate",
        molecularFormula: "CCaO3",
        smiles: "C(=O)([O-])[O-].[Ca+2]",
        molecularWeight: "100.09 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 2,
        boilingPoint: "اطلاعات دقیقی در دسترس نیست",
        meltingPoint: "اطلاعات دقیقی در دسترس نیست",
        density: "اطلاعات دقیقی در دسترس نیست"
    },
    {
        name: "Hematite",
        cid: 14833,
        translate: "هماتیت (سنگ معدن آهن)",
        iupacName: "iron(3+);oxygen(2-)",
        molecularFormula: "Fe2O3",
        smiles: "[O-2].[O-2].[O-2].[Fe+3].[Fe+3]",
        molecularWeight: "159.69 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 5,
        boilingPoint: "اطلاعات دقیقی در دسترس نیست",
        meltingPoint: "اطلاعات دقیقی در دسترس نیست",
        density: "اطلاعات دقیقی در دسترس نیست"
    },
    {
        name: "Bauxite",
        cid: 91889041,
        translate: "بوکسیت (سنگ معدن آلومینیوم)",
        iupacName: "3-methyl-N-[4-(5,6,7,8-tetrahydro-[1,2,4]triazolo[4,3-a]pyridin-3-yl)phenyl]benzamide",
        molecularFormula: "C20H20N4O",
        smiles: "CC1=CC(=CC=C1)C(=O)NC2=CC=C(C=C2)C3=NN=C4N3CCCC4",
        molecularWeight: "332.4 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "اطلاعات دقیقی در دسترس نیست",
        meltingPoint: "اطلاعات دقیقی در دسترس نیست",
        density: "اطلاعات دقیقی در دسترس نیست"
    },
    {
        name: "Silica",
        cid: 24261,
        translate: "سیلیس",
        iupacName: "dioxosilane",
        molecularFormula: "O2Si",
        smiles: "O=[Si]=O",
        molecularWeight: "60.084 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "اطلاعات دقیقی در دسترس نیست",
        meltingPoint: "1710.00 °C",
        density: "2.300 g/cm³"
    },
    {
        name: "Silicon Carbide",
        cid: 9863,
        translate: "سیلیسیم کربید (الماس مصنوعی)",
        iupacName: "methanidylidynesilanylium",
        molecularFormula: "CSi",
        smiles: "[C-]#[Si+]",
        molecularWeight: "40.096 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "اطلاعات دقیقی در دسترس نیست",
        meltingPoint: "اطلاعات دقیقی در دسترس نیست",
        density: "3.200 g/cm³"
    },
    {
        name: "Potassium Permanganate",
        cid: 516875,
        translate: "پتاسیم پرمنگنات",
        iupacName: "potassium;permanganate",
        molecularFormula: "KMnO4",
        smiles: "[O-][Mn](=O)(=O)=O.[K+]",
        molecularWeight: "158.034 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 2,
        boilingPoint: "اطلاعات دقیقی در دسترس نیست",
        meltingPoint: "اطلاعات دقیقی در دسترس نیست",
        density: "اطلاعات دقیقی در دسترس نیست"
    },
    {
        name: "Barium Sulfate",
        cid: 24414,
        translate: "باریم سولفات",
        iupacName: "barium(2+);sulfate",
        molecularFormula: "BaO4S",
        smiles: "[O-]S(=O)(=O)[O-].[Ba+2]",
        molecularWeight: "233.39 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 2,
        boilingPoint: "اطلاعات دقیقی در دسترس نیست",
        meltingPoint: "اطلاعات دقیقی در دسترس نیست",
        density: "اطلاعات دقیقی در دسترس نیست"
    },
    {
        name: "Silver Chloride",
        cid: 24540,
        translate: "نقره کلرید",
        iupacName: "diazanium;hydrogen phosphate",
        molecularFormula: "H9N2O4P",
        smiles: "[NH4+].[NH4+].OP(=O)([O-])[O-]",
        molecularWeight: "132.06 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 3,
        boilingPoint: "اطلاعات دقیقی در دسترس نیست",
        meltingPoint: "اطلاعات دقیقی در دسترس نیست",
        density: "اطلاعات دقیقی در دسترس نیست"
    },
    {
        name: "Ammonium Nitrate",
        cid: 22985,
        translate: "نیترات آمونیوم (کود شیمیایی)",
        iupacName: "azanium;nitrate",
        molecularFormula: "H4N2O3",
        smiles: "[NH4+].[N+](=O)([O-])[O-]",
        molecularWeight: "80.044 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 2,
        boilingPoint: "-260.00 °C",
        meltingPoint: "اطلاعات دقیقی در دسترس نیست",
        density: "1.700 g/cm³"
    },
    {
        name: "Urea",
        cid: 1176,
        translate: "اوره",
        iupacName: "urea",
        molecularFormula: "CH4N2O",
        smiles: "C(=O)(N)N",
        molecularWeight: "60.056 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "اطلاعات دقیقی در دسترس نیست",
        meltingPoint: "132.00 °C",
        density: "اطلاعات دقیقی در دسترس نیست"
    },
    {
        name: "Copper Sulfide",
        cid: 14831,
        translate: "مس سولفید",
        iupacName: "sulfanylidenecopper",
        molecularFormula: "CuS",
        smiles: "S=[Cu]",
        molecularWeight: "95.61 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "اطلاعات دقیقی در دسترس نیست",
        meltingPoint: "اطلاعات دقیقی در دسترس نیست",
        density: "اطلاعات دقیقی در دسترس نیست"
    },
    {
        name: "Polyethylene",
        cid: 23939,
        translate: "پلی‌اتیلن",
        iupacName: "platinum",
        molecularFormula: "Pt",
        smiles: "[Pt]",
        molecularWeight: "195.08 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "3825.00 °C",
        meltingPoint: "اطلاعات دقیقی در دسترس نیست",
        density: "21.450 g/cm³"
    },
    {
        name: "Polypropylene",
        cid: 5360533,
        translate: "پلی‌پروپیلن",
        iupacName: "ندارد",
        molecularFormula: "C10H18NO5",
        smiles: "CC(C)(CO)[C@H](C(=O)NCCCC(=O)[O])O",
        molecularWeight: "232.25 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "اطلاعات دقیقی در دسترس نیست",
        meltingPoint: "اطلاعات دقیقی در دسترس نیست",
        density: "اطلاعات دقیقی در دسترس نیست"
    },
    {
        name: "Polystyrene",
        cid: 8003,
        translate: "پلی‌استایرن",
        iupacName: "pentane",
        molecularFormula: "C5H12",
        smiles: "CCCCC",
        molecularWeight: "72.15 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "36.00 °C",
        meltingPoint: "اطلاعات دقیقی در دسترس نیست",
        density: "اطلاعات دقیقی در دسترس نیست"
    },
    {
        name: "Polytetrafluoroethylene",
        cid: 11347865,
        translate: "تفلون",
        iupacName: "ethyl (4R)-6-fluoro-4-[(2R)-3-methyl-1-oxobutan-2-yl]-2-oxo-3H-1,3-benzoxazine-4-carboxylate",
        molecularFormula: "C16H18FNO5",
        smiles: "CCOC(=O)[C@]1(C2=C(C=CC(=C2)F)OC(=O)N1)[C@H](C=O)C(C)C",
        molecularWeight: "323.32 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "اطلاعات دقیقی در دسترس نیست",
        meltingPoint: "اطلاعات دقیقی در دسترس نیست",
        density: "اطلاعات دقیقی در دسترس نیست"
    },
    {
        name: "Polyvinyl Chloride",
        cid: 68525,
        translate: "پلی‌وینیل کلرید (PVC)",
        iupacName: "N-prop-2-enylaniline",
        molecularFormula: "C9H11N",
        smiles: "C=CCNC1=CC=CC=C1",
        molecularWeight: "133.19 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "اطلاعات دقیقی در دسترس نیست",
        meltingPoint: "اطلاعات دقیقی در دسترس نیست",
        density: "اطلاعات دقیقی در دسترس نیست"
    },
    {
        name: "Polyethylene Terephthalate",
        cid: 8289,
        translate: "پلی‌اتیلن ترفتالات",
        iupacName: "triphenyl phosphate",
        molecularFormula: "C18H15O4P",
        smiles: "C1=CC=C(C=C1)OP(=O)(OC2=CC=CC=C2)OC3=CC=CC=C3",
        molecularWeight: "326.3 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "370.00 °C",
        meltingPoint: "اطلاعات دقیقی در دسترس نیست",
        density: "اطلاعات دقیقی در دسترس نیست"
    },
    {
        name: "Polyacrylonitrile",
        cid: 6328151,
        translate: "پلی‌سیانو اتن",
        iupacName: "ندارد",
        molecularFormula: "C6H13Se",
        smiles: "CCCCCC[Se]",
        molecularWeight: "164.14 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "اطلاعات دقیقی در دسترس نیست",
        meltingPoint: "اطلاعات دقیقی در دسترس نیست",
        density: "اطلاعات دقیقی در دسترس نیست"
    },
    {
        name: "Cellulose",
        cid: 297,
        translate: "سلولز",
        iupacName: "methane",
        molecularFormula: "CH4",
        smiles: "C",
        molecularWeight: "16.043 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "-161.00 °C",
        meltingPoint: "-183.00 °C",
        density: "اطلاعات دقیقی در دسترس نیست"
    }
]
const answerDataBase = {
    "A.10.1": [2, 4, 2, 2, 1, 4, 2, 4, 3, 3, 2, 3, 1, 2, 4, 2, 1, 1, 3, 1, 3, 4, 3, 2, 4, 2, 1, 2, 2, 3],
    "A.10.2": [2, 4, 4, 2, 3, 1, 4, 4, 4, 1, 3, 1, 3, 4, 3, 2, 2, 2, 1, 3, 3, 4, 2, 4, 1, 2, 1, 1, 1, 2, 2, 2, 1, 3, 4, 1, 2, 2, 1, 4, 1, 4, 4, 3, 3, 2, 1, 1, 2, 2, 3, 3, 4, 1, 4, 4, 2, 2, 4, 1, 3, 3, 4, 4, 1, 4, 2],
    "A.10.3": [4, 1, 3, 2, 1, 2, 1, 3, 4, 1, 2, 3, 2, 2, 4, 3, 3, 4, 3, 3, 2, 3, 4, 4, 1, 1, 2, 3, 3, 1, 4, 1, 1, 2, 2, 3, 3, 2, 3, 1, 4, 1, 4, 3, 3, 4, 3, 2, 3, 2, 2, 3, 3, 4, 2, 2, 3, 2, 3, 4, 3, 3, 3, 1, 4, 1],
    "A.11.1": [3, 3, 2, 1, 4, 2, 1, 2, 3, 4, 1, 1, 2, 3, 3, 2, 4, 3, 4, 3, 1, 1, 3, 1, 2, 4, 3, 2, 1, 1, 4, 3, 1, 2, 1, 1, 1, 1, 2, 4, 1, 1, 4, 3, 2, 4, 1, 1, 4, 3, 4, 2, 2, 3, 3, 4, 1, 3, 1, 1, 3, 4, 1, 3, 1, 4, 4, 3, 2],
    "A.11.2": [2, 3, 4, 1, 3, 2, 1, 3, 2, 4, 1, 3, 2, 3, 3, 4, 3, 1, 4, 4, 3, 2, 1, 4, 2, 3, 2, 2, 1, 1, 4, 2, 3, 2, 3, 4, 3, 3, 1, 4, 3, 3, 2, 3, 2, 2, 3, 1, 4, 1, 2, 1, 2, 4, 1, 1, 3, 1, 2, 1, 1, 4, 2, 4, 1, 3, 1, 4, 2, 2, 1, 3, 1],
    "A.11.3": [3, 1, 2, 3, 3, 4, 2, 3, 1, 1, 3, 4, 4, 3, 4, 1, 2, 2, 1, 3, 1, 2, 3, 2, 3, 3, 1, 1, 1, 3, 4, 1, 2, 3, 3, 4, 4, 3, 2, 3, 4, 4, 1],
    "A.12.1": [1, 4, 4, 1, 3, 2, 4, 4, 3, 4, 1, 4, 2, 3, 3, 4, 4, 4, 1, 3, 2, 2, 4, 2, 2, 2, 4, 3, 2, 2, 2, 4, 4, 3, 1, 4, 4, 3, 3, 4, 4, 1, 4, 4, 2, 3, 1, 2, 1, 2, 3],
    "A.12.2": [2, 4, 4, 1, 4, 1, 2, 3, 4, 2, 4, 1, 4, 3, 2, 2, 4, 1, 2, 3, 3, 1, 3, 3, 1, 4, 4, 2, 3, 2, 1, 3, 4, 4, 1, 2, 3, 3, 4, 2, 4, 3, 2, 4, 1, 1, 3, 2, 1, 3, 3, 4, 1, 3, 1, 3, 4, 3, 2, 3, 1, 3, 4, 1, 1, 3, 1, 4, 1, 1, 3, 2, 1],
    "A.12.3": [4, 4, 4, 4, 4, 2, 1, 3, 4, 2, 3, 4, 4, 3, 4, 4, 3, 1, 1, 2, 4, 2, 4, 2, 2, 1, 4, 2, 1, 3, 4, 1, 3, 4],
    "A.12.4": [1, 2, 4, 2, 2, 1, 3, 1, 2, 1, 3, 1, 1, 4, 4, 4, 3, 4, 2, 2, 1, 1, 3, 1, 1, 1, 2, 3, 1, 3, 4, 1, 2, 1, 1, 4, 2, 2, 4, 3, 4, 3, 2,]
}