let themeMode = localStorage.getItem("theme") ?? "light"
const dataBase = [
    {
        name: "Water",
        cid: 962,
        translate: "آب",
        iupacName: "oxidane",
        molecularFormula: "H2O",
        smiles: "O",
        molecularWeight: "18.015 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "100.00 °C",
        meltingPoint: "0.00 °C",
        density: "1.000 g/cm³"
    },
    {
        name: "Oxygen",
        cid: 977,
        translate: "اکسیژن",
        iupacName: "molecular oxygen",
        molecularFormula: "O2",
        smiles: "O=O",
        molecularWeight: "31.998 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "-182.95 °C",
        meltingPoint: "-218.79 °C",
        density: "0.001429 g/cm³"
    },
    {
        name: "Nitrogen",
        cid: 947,
        translate: "نیتروژن",
        iupacName: "molecular nitrogen",
        molecularFormula: "N2",
        smiles: "N#N",
        molecularWeight: "28.014 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "-195.80 °C",
        meltingPoint: "-209.86 °C",
        density: "0.001251 g/cm³"
    },
    {
        name: "Carbon Dioxide",
        cid: 280,
        translate: "دی‌اکسید کربن",
        iupacName: "carbon dioxide",
        molecularFormula: "CO2",
        smiles: "O=C=O",
        molecularWeight: "44.010 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "-78.46 °C",
        meltingPoint: "-56.56 °C",
        density: "0.001977 g/cm³"
    },
    {
        name: "Ozone",
        cid: 24823,
        translate: "اوزون",
        iupacName: "ozone",
        molecularFormula: "O3",
        smiles: "[O-][O+]=O",
        molecularWeight: "47.998 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "-111.90 °C",
        meltingPoint: "-192.50 °C",
        density: "0.002144 g/cm³"
    },
    {
        name: "Methane",
        cid: 297,
        translate: "متان",
        iupacName: "methane",
        molecularFormula: "CH4",
        smiles: "C",
        molecularWeight: "16.043 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "-161.50 °C",
        meltingPoint: "-182.50 °C",
        density: "0.000717 g/cm³"
    },
    {
        name: "Acetylene",
        cid: 6326,
        translate: "اتین (استیلن)",
        iupacName: "ethyne",
        molecularFormula: "C2H2",
        smiles: "C#C",
        molecularWeight: "26.038 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "-84.70 °C",
        meltingPoint: "-80.80 °C",
        density: "0.001165 g/cm³"
    },
    {
        name: "Ethylene",
        cid: 6325,
        translate: "اتن (اتیلن)",
        iupacName: "ethene",
        molecularFormula: "C2H4",
        smiles: "C=C",
        molecularWeight: "28.054 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "-103.70 °C",
        meltingPoint: "-169.20 °C",
        density: "0.001178 g/cm³"
    },
    {
        name: "Butane",
        cid: 7843,
        translate: "بوتان",
        iupacName: "butane",
        molecularFormula: "C4H10",
        smiles: "CCCC",
        molecularWeight: "58.122 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "-0.50 °C",
        meltingPoint: "-138.30 °C",
        density: "0.00248 g/cm³"
    },
    {
        name: "Cyclohexane",
        cid: 8078,
        translate: "سیکلوهگزان",
        iupacName: "cyclohexane",
        molecularFormula: "C6H12",
        smiles: "C1CCCCC1",
        molecularWeight: "84.160 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "80.74 °C",
        meltingPoint: "6.47 °C",
        density: "0.779 g/cm³"
    },
    {
        name: "Ammonia",
        cid: 222,
        translate: "آمونیاک",
        iupacName: "azane",
        molecularFormula: "NH3",
        smiles: "N",
        molecularWeight: "17.031 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "-33.34 °C",
        meltingPoint: "-77.73 °C",
        density: "0.000771 g/cm³"
    },
    {
        name: "Carbon Monoxide",
        cid: 281,
        translate: "مونوکسید کربن",
        iupacName: "carbon monoxide",
        molecularFormula: "CO",
        smiles: "[C-]#[O+]",
        molecularWeight: "28.010 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "-191.50 °C",
        meltingPoint: "-205.00 °C",
        density: "0.00125 g/cm³"
    },
    {
        name: "Hydrogen Peroxide",
        cid: 784,
        translate: "هیدروژن پراکسید",
        iupacName: "hydrogen peroxide",
        molecularFormula: "H2O2",
        smiles: "OO",
        molecularWeight: "34.015 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "150.20 °C",
        meltingPoint: "-0.43 °C",
        density: "1.442 g/cm³"
    },
    {
        name: "Carbonyl Sulfide",
        cid: 10039,
        translate: "کربونیل سولفید",
        iupacName: "carbonyl sulfide",
        molecularFormula: "COS",
        smiles: "C(=O)=S",
        molecularWeight: "60.075 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "-50.20 °C",
        meltingPoint: "-138.80 °C",
        density: "0.00251 g/cm³"
    },
    {
        name: "Dinitrogen Oxide",
        cid: 948,
        translate: "دی‌نیتروژن اکسید",
        iupacName: "nitrous oxide",
        molecularFormula: "N2O",
        smiles: "N#N=O",
        molecularWeight: "44.013 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "-88.48 °C",
        meltingPoint: "-90.86 °C",
        density: "0.001977 g/cm³"
    },
    {
        name: "Hydrochloric Acid",
        cid: 313,
        translate: "هیدروکلریک اسید (جوهر نمک)",
        iupacName: "hydrogen chloride",
        molecularFormula: "HCl",
        smiles: "Cl",
        molecularWeight: "36.461 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "-85.05 °C",
        meltingPoint: "-114.20 °C",
        density: "0.00149 g/cm³"
    },
    {
        name: "Sulfuric Acid",
        cid: 1118,
        translate: "سولفوریک اسید",
        iupacName: "sulfuric acid",
        molecularFormula: "H2SO4",
        smiles: "OS(=O)(=O)O",
        molecularWeight: "98.079 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "337.00 °C",
        meltingPoint: "10.31 °C",
        density: "1.840 g/cm³"
    },
    {
        name: "Nitric Acid",
        cid: 944,
        translate: "نیتریک اسید",
        iupacName: "nitric acid",
        molecularFormula: "HNO3",
        smiles: "O[N+](=O)[O-]",
        molecularWeight: "63.013 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "120.50 °C",
        meltingPoint: "-41.60 °C",
        density: "1.512 g/cm³"
    },
    {
        name: "Phosphoric Acid",
        cid: 1004,
        translate: "فسفریک اسید",
        iupacName: "phosphoric acid",
        molecularFormula: "H3PO4",
        smiles: "OP(=O)(O)O",
        molecularWeight: "97.995 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "213.00 °C",
        meltingPoint: "42.35 °C",
        density: "1.885 g/cm³"
    },
    {
        name: "Formic Acid",
        cid: 284,
        translate: "فورمیک اسید (متانوئیک اسید)",
        iupacName: "formic acid",
        molecularFormula: "HCOOH",
        smiles: "C(=O)O",
        molecularWeight: "46.025 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "100.80 °C",
        meltingPoint: "8.40 °C",
        density: "1.220 g/cm³"
    },
    {
        name: "Acetic Acid",
        cid: 176,
        translate: "استیک اسید (اتانوییک اسید)",
        iupacName: "acetic acid",
        molecularFormula: "CH3COOH",
        smiles: "CC(=O)O",
        molecularWeight: "60.052 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "117.90 °C",
        meltingPoint: "16.60 °C",
        density: "1.049 g/cm³"
    },
    {
        name: "Hydrocyanic Acid",
        cid: 768,
        translate: "هیدروسیانیک اسید",
        iupacName: "hydrogen cyanide",
        molecularFormula: "HCN",
        smiles: "C#N",
        molecularWeight: "27.025 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "25.70 °C",
        meltingPoint: "-13.30 °C",
        density: "0.687 g/cm³"
    },
    {
        name: "Hydrofluoric Acid",
        cid: 14917,
        translate: "هیدروفلوئوریک اسید",
        iupacName: "hydrogen fluoride",
        molecularFormula: "HF",
        smiles: "F",
        molecularWeight: "20.006 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "19.50 °C",
        meltingPoint: "-83.60 °C",
        density: "0.00115 g/cm³"
    },
    {
        name: "Hydrobromic Acid",
        cid: 260,
        translate: "هیدروبرمیک اسید",
        iupacName: "hydrogen bromide",
        molecularFormula: "HBr",
        smiles: "Br",
        molecularWeight: "80.912 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "-66.80 °C",
        meltingPoint: "-86.90 °C",
        density: "0.003645 g/cm³"
    },
    {
        name: "Hydroiodic Acid",
        cid: 24841,
        translate: "هیدرویدیک اسید",
        iupacName: "hydrogen iodide",
        molecularFormula: "HI",
        smiles: "I",
        molecularWeight: "127.912 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "-35.40 °C",
        meltingPoint: "-50.80 °C",
        density: "0.00566 g/cm³"
    },
    {
        name: "Carbonic Acid",
        cid: 767,
        translate: "کربنیک اسید",
        iupacName: "carbonic acid",
        molecularFormula: "H2CO3",
        smiles: "OC(=O)O",
        molecularWeight: "62.025 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "تجزیه می‌شود",
        meltingPoint: "تجزیه می‌شود",
        density: "1.668 g/cm³"
    },
    {
        name: "Methanol",
        cid: 887,
        translate: "متانول (الکل چوب)",
        iupacName: "methanol",
        molecularFormula: "CH3OH",
        smiles: "CO",
        molecularWeight: "32.042 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "64.70 °C",
        meltingPoint: "-97.60 °C",
        density: "0.792 g/cm³"
    },
    {
        name: "Ethanol",
        cid: 702,
        translate: "اتانول (الکل طبی)",
        iupacName: "ethanol",
        molecularFormula: "C2H5OH",
        smiles: "CCO",
        molecularWeight: "46.069 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "78.37 °C",
        meltingPoint: "-114.10 °C",
        density: "0.789 g/cm³"
    },
    {
        name: "Ethylene Glycol",
        cid: 174,
        translate: "اتیلن گلیکول (ضدیخ)",
        iupacName: "ethane-1,2-diol",
        molecularFormula: "C2H6O2",
        smiles: "OCCO",
        molecularWeight: "62.068 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "197.30 °C",
        meltingPoint: "-12.90 °C",
        density: "1.113 g/cm³"
    },
    {
        name: "Acetone",
        cid: 180,
        translate: "استون (پروپانون)",
        iupacName: "propan-2-one",
        molecularFormula: "C3H6O",
        smiles: "CC(=O)C",
        molecularWeight: "58.079 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "56.00 °C",
        meltingPoint: "-94.70 °C",
        density: "0.791 g/cm³"
    },
    {
        name: "Benzaldehyde",
        cid: 240,
        translate: "بنزآلدهید (موجود در بادام)",
        iupacName: "benzaldehyde",
        molecularFormula: "C7H6O",
        smiles: "C1=CC=C(C=C1)C=O",
        molecularWeight: "106.122 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "178.10 °C",
        meltingPoint: "-26.00 °C",
        density: "1.045 g/cm³"
    },
    {
        name: "2-Heptanone",
        cid: 8051,
        translate: "هپتانون-۲ (موجود در میخک)",
        iupacName: "heptan-2-one",
        molecularFormula: "C7H14O",
        smiles: "CCCCC(=O)CC",
        molecularWeight: "114.186 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "151.50 °C",
        meltingPoint: "-35.50 °C",
        density: "0.811 g/cm³"
    },
    {
        name: "Aspirin",
        cid: 2244,
        translate: "آسپرین",
        iupacName: "2-acetyloxybenzoic acid",
        molecularFormula: "C9H8O4",
        smiles: "CC(=O)OC1=CC=CC=C1C(=O)O",
        molecularWeight: "180.157 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "تجزیه می‌شود",
        meltingPoint: "135.00 °C",
        density: "1.400 g/cm³"
    },
    {
        name: "Glucose",
        cid: 5793,
        translate: "گلوکز",
        iupacName: "(2R,3S,4R,5R)-2,3,4,5,6-pentahydroxyhexanal",
        molecularFormula: "C6H12O6",
        smiles: "C([C@@H]1[C@H]([C@@H]([C@H](C(O1)O)O)O)O)O",
        molecularWeight: "180.156 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "تجزیه می‌شود",
        meltingPoint: "146.00 °C",
        density: "1.540 g/cm³"
    },
    {
        name: "Maltose",
        cid: 6255,
        translate: "مالتوز (قند جوانه گندم)",
        iupacName: "4-O-alpha-D-glucopyranosyl-D-glucose",
        molecularFormula: "C12H22O11",
        smiles: "C([C@@H]1[C@H]([C@@H]([C@H]([C@H](O1)O[C@@H]2[C@H](O[C@H]([C@@H]([C@H]2O)O)O)CO)O)O)O)O",
        molecularWeight: "342.297 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "تجزیه می‌شود",
        meltingPoint: "160.00 °C",
        density: "1.540 g/cm³"
    },
    {
        name: "Oleic Acid",
        cid: 445639,
        translate: "روغن زیتون",
        iupacName: "(Z)-octadec-9-enoic acid",
        molecularFormula: "C18H34O2",
        smiles: "CCCCCCCC/C=C\\CCCCCCCC(=O)O",
        molecularWeight: "282.461 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "360.00 °C",
        meltingPoint: "13.40 °C",
        density: "0.895 g/cm³"
    },
    {
        name: "Stearin",
        cid: 11146,
        translate: "چربی کوهان شتر",
        iupacName: "2,3-di(octadecanoyloxy)propyl octadecanoate",
        molecularFormula: "C57H110O6",
        smiles: "CCCCCCCCCCCCCCCCCC(=O)OCC(COC(=O)CCCCCCCCCCCCCCCCC)OC(=O)CCCCCCCCCCCCCCCCC",
        molecularWeight: "891.484 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "تجزیه می‌شود",
        meltingPoint: "71.00 °C",
        density: "0.940 g/cm³"
    },
    {
        name: "Benzene",
        cid: 241,
        translate: "بنزن",
        iupacName: "benzene",
        molecularFormula: "C6H6",
        smiles: "C1=CC=CC=C1",
        molecularWeight: "78.112 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "80.10 °C",
        meltingPoint: "5.53 °C",
        density: "0.879 g/cm³"
    },
    {
        name: "Naphthalene",
        cid: 931,
        translate: "نفتالن",
        iupacName: "naphthalene",
        molecularFormula: "C10H8",
        smiles: "C1=CC=C2C=CC=CC2=C1",
        molecularWeight: "128.171 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "218.00 °C",
        meltingPoint: "80.26 °C",
        density: "1.162 g/cm³"
    },
    {
        name: "p-Xylene",
        cid: 7809,
        translate: "پارازایلن",
        iupacName: "1,4-dimethylbenzene",
        molecularFormula: "C8H10",
        smiles: "CC1=CC=C(C=C1)C",
        molecularWeight: "106.165 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "138.40 °C",
        meltingPoint: "13.30 °C",
        density: "0.861 g/cm³"
    },
    {
        name: "Styrene",
        cid: 7501,
        translate: "استایرن",
        iupacName: "styrene",
        molecularFormula: "C8H8",
        smiles: "C=CC1=CC=CC=C1",
        molecularWeight: "104.149 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "145.20 °C",
        meltingPoint: "-30.60 °C",
        density: "0.906 g/cm³"
    },
    {
        name: "Propene",
        cid: 8252,
        translate: "پروپن",
        iupacName: "prop-1-ene",
        molecularFormula: "C3H6",
        smiles: "CC=C",
        molecularWeight: "42.080 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "-47.60 °C",
        meltingPoint: "-185.20 °C",
        density: "0.00181 g/cm³"
    },
    {
        name: "Octadecane",
        cid: 11635,
        translate: "گریس",
        iupacName: "octadecane",
        molecularFormula: "C18H38",
        molecularFormula: "C18H38",
        smiles: "CCCCCCCCCCCCCCCCCC",
        molecularWeight: "254.494 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "316.00 °C",
        meltingPoint: "28.20 °C",
        density: "0.777 g/cm³"
    },
    {
        name: "Petrolatum",
        cid: 4,
        translate: "وازلین",
        iupacName: "petrolatum",
        molecularFormula: "مخلوط هیدروکربن‌ها",
        smiles: "ندارد",
        molecularWeight: "متغیر",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "تجزیه می‌شود",
        meltingPoint: "38.00 °C تا 60.00 °C",
        density: "0.840 g/cm³"
    },
    {
        name: "Sodium Hydroxide",
        cid: 14798,
        translate: "سدیم هیدروکسید (سود سوزآور)",
        iupacName: "sodium hydroxide",
        molecularFormula: "NaOH",
        smiles: "[Na+].[OH-]",
        molecularWeight: "39.997 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 2,
        boilingPoint: "1388.00 °C",
        meltingPoint: "323.00 °C",
        density: "2.130 g/cm³"
    },
    {
        name: "Potassium Hydroxide",
        cid: 14797,
        translate: "پتاسیم هیدروکسید (پتاس سوزآور)",
        iupacName: "potassium hydroxide",
        molecularFormula: "KOH",
        smiles: "[K+].[OH-]",
        molecularWeight: "56.106 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 2,
        boilingPoint: "1327.00 °C",
        meltingPoint: "406.00 °C",
        density: "2.044 g/cm³"
    },
    {
        name: "Sodium Bicarbonate",
        cid: 516892,
        translate: "سدیم هیدروژن کربنات (جوش شیرین)",
        iupacName: "sodium hydrogen carbonate",
        molecularFormula: "NaHCO3",
        smiles: "[Na+].C(=O)([O-])O",
        molecularWeight: "84.007 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 2,
        boilingPoint: "تجزیه می‌شود",
        meltingPoint: "50.00 °C",
        density: "2.200 g/cm³"
    },
    {
        name: "Calcium Oxide",
        cid: 14778,
        translate: "آهک (کلسیم اکسید)",
        iupacName: "calcium oxide",
        molecularFormula: "CaO",
        smiles: "[Ca+2].[O-2]",
        molecularWeight: "56.077 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 2,
        boilingPoint: "2850.00 °C",
        meltingPoint: "2613.00 °C",
        density: "3.340 g/cm³"
    },
    {
        name: "Calcium Carbonate",
        cid: 10112,
        translate: "کربنات کلسیم",
        iupacName: "calcium carbonate",
        molecularFormula: "CaCO3",
        smiles: "[Ca+2].C(=O)([O-])[O-]",
        molecularWeight: "100.087 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 2,
        boilingPoint: "تجزیه می‌شود",
        meltingPoint: "1339.00 °C",
        density: "2.711 g/cm³"
    },
    {
        name: "Hematite",
        cid: 14833,
        translate: "هماتیت (سنگ معدن آهن)",
        iupacName: "iron(III) oxide",
        molecularFormula: "Fe2O3",
        smiles: "[Fe+3].[Fe+3].[O-2].[O-2].[O-2]",
        molecularWeight: "159.688 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 5,
        boilingPoint: "تجزیه می‌شود",
        meltingPoint: "1565.00 °C",
        density: "5.250 g/cm³"
    },
    {
        name: "Bauxite",
        cid: 14792,
        translate: "بوکسیت (سنگ معدن آلومینیوم)",
        iupacName: "aluminum oxide",
        molecularFormula: "Al2O3",
        smiles: "[Al+3].[Al+3].[O-2].[O-2].[O-2]",
        molecularWeight: "101.961 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 5,
        boilingPoint: "2977.00 °C",
        meltingPoint: "2072.00 °C",
        density: "3.987 g/cm³"
    },
    {
        name: "Silica",
        cid: 24261,
        translate: "سیلیس",
        iupacName: "silicon dioxide",
        molecularFormula: "SiO2",
        smiles: "O=[Si]=O",
        molecularWeight: "60.084 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "2230.00 °C",
        meltingPoint: "1713.00 °C",
        density: "2.650 g/cm³"
    },
    {
        name: "Silicon Carbide",
        cid: 9863,
        translate: "سیلیسیم کربید (الماس مصنوعی)",
        iupacName: "silicon carbide",
        molecularFormula: "SiC",
        smiles: "[Si]#[C]",
        molecularWeight: "40.096 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "تجزیه می‌شود",
        meltingPoint: "2730.00 °C",
        density: "3.210 g/cm³"
    },
    {
        name: "Potassium Permanganate",
        cid: 516875,
        translate: "پتاسیم پرمنگنات",
        iupacName: "potassium permanganate",
        molecularFormula: "KMnO4",
        smiles: "[K+].[O-][Mn](=O)(=O)=O",
        molecularWeight: "158.034 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 2,
        boilingPoint: "تجزیه می‌شود",
        meltingPoint: "240.00 °C",
        density: "2.703 g/cm³"
    },
    {
        name: "Barium Sulfate",
        cid: 24414,
        translate: "باریم سولفات",
        iupacName: "barium sulfate",
        molecularFormula: "BaSO4",
        smiles: "[Ba+2].[O-]S(=O)(=O)[O-]",
        molecularWeight: "233.390 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 2,
        boilingPoint: "تجزیه می‌شود",
        meltingPoint: "1580.00 °C",
        density: "4.500 g/cm³"
    },
    {
        name: "Silver Chloride",
        cid: 24561,
        translate: "نقره کلرید",
        iupacName: "silver chloride",
        molecularFormula: "AgCl",
        smiles: "[Ag+].[Cl-]",
        molecularWeight: "143.321 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 2,
        boilingPoint: "1550.00 °C",
        meltingPoint: "455.00 °C",
        density: "5.560 g/cm³"
    },
    {
        name: "Ammonium Nitrate",
        cid: 22985,
        translate: "نیترات آمونیوم (کود شیمیایی)",
        iupacName: "ammonium nitrate",
        molecularFormula: "NH4NO3",
        smiles: "[NH4+].[N+](=O)([O-])[O-]",
        molecularWeight: "80.043 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 2,
        boilingPoint: "تجزیه می‌شود",
        meltingPoint: "169.60 °C",
        density: "1.720 g/cm³"
    },
    {
        name: "Urea",
        cid: 1176,
        translate: "اوره",
        iupacName: "urea",
        molecularFormula: "CH4N2O",
        smiles: "C(=O)(N)N",
        molecularWeight: "60.055 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "تجزیه می‌شود",
        meltingPoint: "133.00 °C",
        density: "1.323 g/cm³"
    },
    {
        name: "Copper Sulfide",
        cid: 14831,
        translate: "مس سولفید",
        iupacName: "copper(II) sulfide",
        molecularFormula: "CuS",
        smiles: "[Cu+2].[S-2]",
        molecularWeight: "95.611 g/mol",
        isotopeAtomCount: 0,
        covalentUnitCount: 2,
        boilingPoint: "تجزیه می‌شود",
        meltingPoint: "220.00 °C",
        density: "4.760 g/cm³"
    },
    {
        name: "Polyethylene",
        cid: 24868911,
        translate: "پلی‌اتیلن",
        iupacName: "poly(ethene)",
        molecularFormula: "C2H4",
        smiles: "CC",
        molecularWeight: "متغیر",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "تجزیه می‌شود",
        meltingPoint: "130.00 °C",
        density: "0.950 g/cm³"
    },
    {
        name: "Polypropylene",
        cid: 24868912,
        translate: "پلی‌پروپیلن",
        iupacName: "poly(prop-1-ene)",
        molecularFormula: "C3H6",
        smiles: "CC=C",
        molecularWeight: "متغیر",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "تجزیه می‌شود",
        meltingPoint: "160.00 °C",
        density: "0.900 g/cm³"
    },
    {
        name: "Polystyrene",
        cid: 24868913,
        translate: "پلی‌استایرن",
        iupacName: "poly(styrene)",
        molecularFormula: "C8H8",
        smiles: "c1ccccc1CC",
        molecularWeight: "متغیر",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "تجزیه می‌شود",
        meltingPoint: "240.00 °C",
        density: "1.050 g/cm³"
    },
    {
        name: "Polytetrafluoroethylene",
        cid: 24868914,
        translate: "تفلون",
        iupacName: "poly(tetrafluoroethene)",
        molecularFormula: "C2F4",
        smiles: "C(F)(F)C(F)(F)",
        molecularWeight: "متغیر",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "تجزیه می‌شود",
        meltingPoint: "327.00 °C",
        density: "2.200 g/cm³"
    },
    {
        name: "Polyvinyl Chloride",
        cid: 24868915,
        translate: "پلی‌وینیل کلرید (PVC)",
        iupacName: "poly(chloroethene)",
        molecularFormula: "C2H3Cl",
        smiles: "CCCl",
        molecularWeight: "متغیر",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "تجزیه می‌شود",
        meltingPoint: "100.00 °C تا 260.00 °C",
        density: "1.400 g/cm³"
    },
    {
        name: "Polyethylene Terephthalate",
        cid: 24868916,
        translate: "پلی‌اتیلن ترفتالات",
        iupacName: "poly(oxyethyleneoxyterephthaloyl)",
        molecularFormula: "C10H8O4",
        smiles: "c1cc(ccc1C(=O)OCCO)C(=O)O",
        molecularWeight: "متغیر",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "تجزیه می‌شود",
        meltingPoint: "250.00 °C",
        density: "1.380 g/cm³"
    },
    {
        name: "Polyacrylonitrile",
        cid: 24868917,
        translate: "پلی‌اکریلونیتریل",
        iupacName: "poly(prop-2-enenitrile)",
        molecularFormula: "C3H3N",
        smiles: "CC(C#N)",
        molecularWeight: "متغیر",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "تجزیه می‌شود",
        meltingPoint: "317.00 °C",
        density: "1.184 g/cm³"
    },
    {
        name: "Cellulose",
        cid: 60789,
        translate: "سلولز",
        iupacName: "cellulose",
        molecularFormula: "C6H10O5",
        smiles: "OCC1OC(OC2C(O)C(O)C(Oc3c(O)c(O)c(O)c(c3O)OC4C(O)C(O)C(OC5C(O)C(O)C(O)C(O5)CO)OC4CO)OC2CO)C(O)C(O)C1O",
        molecularWeight: "متغیر",
        isotopeAtomCount: 0,
        covalentUnitCount: 1,
        boilingPoint: "تجزیه می‌شود",
        meltingPoint: "تجزیه می‌شود",
        density: "1.500 g/cm³"
    }
];
const answerDataBase = {
    "A.10.1": [2, 4, 2, 2, 1, 4, 2, 4, 3, 3, 2, 3, 1, 2, 4, 2, 1, 1, 3, 1, 3, 4, 3, 2, 4, 2, 1, 2, 2, 3],
    "A.10.2": [2, 4, 4, 2, 3, 1, 4, 4, 4, 1, 3, 1, 3, 4, 3, 2, 2, 2, 1, 3, 3, 4, 2, 4, 1, 2, 1, 1, 1, 2, 2, 2, 1, 3, 4, 1, 2, 2, 1, 4, 1, 4, 4, 3, 3, 2, 1, 1, 2, 2, 3, 3, 4, 1, 4, 4, 2, 2, 4, 1, 3, 3, 4, 4, 1, 4, 2],
    "A.10.3": [4, 1, 3, 2, 1, 2, 1, 3, 4, 1, 2, 3, 2, 2, 4, 3, 3, 4, 3, 3, 2, 3, 4, 4, 1, 1, 2, 3, 3, 1, 4, 1, 1, 2, 2, 3, 3, 2, 3, 1, 4, 1, 4, 3, 3, 4, 3, 2, 3, 2, 2, 3, 3, 4, 2, 2, 3, 2, 3, 4, 3, 3, 3, 1, 4, 1],
    "A.11.1": [3, 3, 2, 1, 4, 2, 1, 2, 3, 4, 1, 1, 2, 3, 3, 2, 4, 3, 4, 3, 1, 1, 3, 1, 2, 4, 3, 2, 1, 1, 4, 3, 1, 2, 1, 1, 1, 1, 2, 4, 1, 1, 4, 3, 2, 4, 1, 1, 4, 3, 4, 2, 2, 3, 3, 4, 1, 3, 1, 1, 3, 4, 1, 3, 1, 4, 4, 3, 2],
    "A.11.2": [2, 3, 4, 1, 3, 2, 1, 3, 2, 4, 1, 3, 2, 3, 3, 4, 3, 1, 4, 4, 3, 2, 1, 4, 2, 3, 2, 2, 1, 1, 4, 2, 3, 2, 3, 4, 3, 3, 1, 4, 3, 3, 2, 3, 2, 2, 3, 1, 4, 1, 2, 1, 2, 4, 1, 1, 3, 1, 2, 1, 1, 4, 2, 4, 1, 3, 1, 4, 2, 2, 1, 3, 1],
    "A.11.3": [3, 1, 2, 3, 3, 4, 2, 3, 1, 1, 3, 4, 4, 3, 4, 1, 2, 2, 1, 3, 1, 2, 3, 2, 3, 3, 1, 1, 1, 3, 4, 1, 2, 3, 3, 4, 4, 3, 2, 3, 4, 4, 1],
    "A.12.1": [1, 4, 4, 1, 3, 2, 4, 4, 3, 4, 1, 4, 2, 3, 3, 4, 4, 4, 1, 3, 2, 2, 4, 2, 2, 2, 4, 3, 2, 2, 2, 4, 4, 3, 1, 4, 4, 3, 3, 4, 4, 1, 4, 4, 2, 3, 1, 2, 1, 2, 3],
    "A.12.2": [2, 4, 4, 1, 4, 1, 2, 3, 4, 2, 4, 1, 4, 3, 2, 2, 4, 1, 2, 3, 3, 1, 3, 3, 1, 4, 4, 2, 3, 2, 1, 3, 4, 4, 1, 2, 3, 3, 4, 2, 4, 3, 2, 4, 1, 1, 3, 2, 1, 3, 3, 4, 1, 3, 1, 3, 4, 3, 2, 3, 1, 3, 4, 1, 1, 3, 1, 4, 1, 1, 3, 2, 1],
    "A.12.3": [4, 4, 4, 4, 4, 2, 1, 3, 4, 2, 3, 4, 4, 3, 4, 4, 3, 1, 1, 2, 4, 2, 4, 2, 2, 1, 4, 2, 1, 3, 4, 1, 3, 4],
    "A.12.4": [1, 2, 4, 2, 2, 1, 3, 1, 2, 1, 3, 1, 1, 4, 4, 4, 3, 4, 2, 2, 1, 1, 3, 1, 1, 1, 2, 3, 1, 3, 4, 1, 2, 1, 1, 4, 2, 2, 4, 3, 4, 3, 2,]
}